services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://backend:3001
    image: tronghieu888/my-fullstack-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: tronghieu888/my-fullstack-backend:latest
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=mysql://root:admin123@db:3306/fullstack-docker-app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3001

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: fullstack-docker-app
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql-data:
